init:
	cd ..
	powershell -Command Write-Host -ForegroundColor green "Hello World"

do-this:
	powershell -Command ls

build:
	powershell -Command Write-Host "Building module"

run:
	python -c "print('Hello World!')"

.PHONY: init